name: Build & Lint

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "!.github/workflows/build.yml"
      - ".vscode/**"
      - ".gitignore"
      - "README.md"
  pull_request:

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Mise
        uses: immich-app/devtools/actions/use-mise@7b8610a904d57da241e4ddba17fa62b62b15aed4 # use-mise-action-v2.0.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout assets
        run: mise assets

      - name: Install dependencies
        run: mise install:frozen

      - name: Lint
        run: mise lint

      - name: Format
        run: mise format

      - name: Build
        run: mise build
